[workspace]
authors = ["Tom Mariani <tom.mariani.dev@gmail.com>"]
channels = ["conda-forge"]
name = "single-cell-tracking-analysis"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.1.0,<8"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.3.5,<3"
scikit-learn = ">=1.7.2,<2"
